import { GridRowSelectionModel } from "@mui/x-data-grid";
import dayjs, { Dayjs } from 'dayjs';
import { IQuestion, IQuiz, RewardType } from "./Quiz";
import { IAssessment } from "./Assessment";
import { Student } from "./Student";
import { IJob } from "./Job";
import { Group } from "./Group";

export enum EvaluatorType {
    SelfAssessment = 0,
    PeerEvaluation = 1,
    ClientEvaluation = 2,
}

export interface IAssessmentResultPage {
    pageNum: number;
    responses: {
        _id: string;
        quizItem: string | IQuestion; // Reference to the question ID
        response?: string; // The actual response given by the evaluator (QuizItem.Option._id)
        likert_response?: { [key: string]: string }; // The actual response given by the evaluator for likert scale question
        options?: IQuestion['options'];
        op_answer?: string; // Optional open-ended response
        // correct?: boolean; // Optional attribute for marking correctness
        mark?: number; // Optional override mark given for the response
        completed: boolean;
        questionNum?: number;
        rewards?: IQuestion['rewards'];
    }[];
    completed?: boolean;
}

export interface IAssessmentResult {
    _id?: string;
    currentPage?: number;
    pages: IAssessmentResultPage[];
    evaluator: {
        name?: string; // populated from user by server
        label?: string; // dynamically generated by server (e.g. name + matric number)
        type: EvaluatorType; // Type of evaluator
        evaluator_id: string; // Reference to evaluator ID
        access_code: string;
        evaluator?: {
            _id?: string;
            name?: string;
            matricNumber?: string;
        };
    };
    evaluatee?: Student | Group | string; // only for peer and client evaluation
    assessment: string | IAssessment;
    completed: boolean; // Completion status
    startedAt?: Date;
    endedAt?: Date;
    duration?: string;
    serverClock?: Date;
    timeLeft?: number;
    canSubmit?: boolean;
    order?: number; // the correct order when result is sorted in an array
    totalRewards: {[RewardType.POINT]: number, [RewardType.SCORE]: number};
    emailJob: IJob;
    lastPage?: number;
}

export interface IAssessmentResultMultiple {
    quiz?: IQuiz;
    results: IAssessmentResult[];
    canSubmitAll: boolean; // true if all results' canSubmit is true
}

export interface IAssessmentResultWithEvaluatees {
    result: IAssessmentResult;
    evaluatees?: Student[]; // include list of all student ids to be evaluatd by the evaluator
}