# docker-compose.yml
services:
  frontend:
    build:
      context: ./client/sotl
      dockerfile: Dockerfile
      target: production
    stdin_open: true
    ports:
      - "3000:80"
    restart: always
    networks:
      - mern-app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    environment:
      - BACKEND_PORT=5000
    volumes:
      - ./server:/app/src
      - /app/src/node_modules
    # restart: 
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  
